name: 'Build Project'
description: 'Composite action example using "uses" to build the project'
inputs:
  java-version:
    required: true
    description: 'The version of Java to use'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{inputs.java-version}}
      uses: actions/setup-java@v3
      with:
        java-version: ${{inputs.java-version}}
        distribution: 'zulu'
        cache: 'maven'
    - name: Maven Package
      run: mvn package --file pom.xml
      shell: bash
