name: Java CI

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Project
        uses: ./.github/actions/build-project
        with:
          java-version: 11
